### ISSUE TITLE
Reboot and Sleep05 counter always show ZERO

### ISSUE THREAD

**Issue by pesor** [pesor/LilyGO-TTGO-HiGrow#2]
Known flaw in program:

At the moment the reboot and sleep5 counter does always show ZERO.
This flaw will be corrected in version 1.7

**Comment by BeardedTinker** [comment]
My boot counter is updating every time I get new data from sensor.

**Comment by pesor** [comment]
Hi Andrej,

Just checked my latest version 1.6, and you are right, it increments????????????????????????

Reading the code, it should be impossible, BUT

As I do as all do, copy an example of code and change it to my need, I found out that I have the following statement for the bootCount variable:

RTC_DATA_ATTR int bootCount = 0;

I had no idea why it stated RTC_DATA_ATTR  before the variable name, but now I have googled it, and that statement saves the variable in memory when esp32 goes to sleep, and retains it, when esp32 wakes up again.

That is very smart, and something I definitively will use in other programs.

I will in next release of the software, make same statement for the variable sleep5no.

I am working successfully with the Autodiscover, and when finished, you only in the YAML file, will have to write the following three statements:

Sensor:
  - platform: mqtt
    name: West_Vindow_Soil_1
    state_topic: "westWindow/West_1"

Here for the first plant in my West Window, and then ALL the sensors will be added to Homeassistant automatically:

You only need to add the Python program folder “TIGO-HIGrow" to folder “custom_components” in your Homeassistant configure folder. This folder will be part of my Github repository.

This will save me for several hundred lines of code in my configuration.yaml file.

I hope to be finished with it all, within the next 7-10 days.

Best regards,
Per




Fra: BeardedTinker <notifications@github.com>
Sendt: 1. august 2020 21:52
Til: pesor/LilyGO-TTGO-HiGrow <LilyGO-TTGO-HiGrow@noreply.github.com>
Cc: Per Rose <post@per-rose.dk>; Assign <assign@noreply.github.com>
Emne: Re: [pesor/LilyGO-TTGO-HiGrow] Reboot and Sleep05 counter always show ZERO (#2)


My boot counter is updating every time I get new data from sensor.

**Comment by BeardedTinker** [comment]
If you remember, I once mentioned Device ID - that is getChipID() function that outputs unique ID of every ESP chip.
It really is MAC address, but for what it's worth, it's unique :)
By using this as topic in line with this: https://www.home-assistant.io/docs/mqtt/discovery/ 
It would be possible to have only WiFi and MQTT configuration inside .ino file, and everything else handled by Home Assistant.
You just rename MAC/Unique ID to what you want it to be - and all sensors get same name.
At least I think that it would work. 
And you can select location for every device inside HA already, so no need to do that in configuration of HiGorw sensor too.
If you would move sensor or put it wit another plant, you just rename inside HA, and no need to flash device once again.

**Comment by pesor** [comment]
Hi Andrej,

With your latest configuration video, it makes sense to have a generic name for the sensor, like eg the MAC address.

I have been reading the documation, but it is a little Chinese to me, so I am going to make it in two steps.

I will change the INO to use MAC, and test that in the Python customs program I am writing.

When that works, I have completed step 1.

I hope then I can transfer this step into the autodiscovery, but I am not sure it is as simple as just have the Autodiscover on, to me it looks like something has to be filled into an YAML file, which is maybe more complicated than just having the

  *   Platform: mqtt
Topic: (MAC code without spaces)

Then your latest video configuration with name and sensors etc, shall be used.

Which will be my goal right now.

Hope that is OK, for at start.

It will mean that you will have to install my Python folder into custom_components, Which I know that this is what you want to avoid.

Next step will have to find out how to integrate Autodiscover.

But let’s talk along the development route, maybe we will be able to catch two flies in one smack.

Regards,
Per

Fra: BeardedTinker <notifications@github.com>
Sendt: 3. august 2020 21:57
Til: pesor/LilyGO-TTGO-HiGrow <LilyGO-TTGO-HiGrow@noreply.github.com>
Cc: Per Rose <post@per-rose.dk>; Assign <assign@noreply.github.com>
Emne: Re: [pesor/LilyGO-TTGO-HiGrow] Reboot and Sleep05 counter always show ZERO (#2)


If you remember, I once mentioned Device ID - that is getChipID() function that outputs unique ID of every ESP chip.
It really is MAC address, but for what it's worth, it's unique :)
By using this as topic in line with this: https://www.home-assistant.io/docs/mqtt/discovery/
It would be possible to have only WiFi and MQTT configuration inside .ino file, and everything else handled by Home Assistant.
You just rename MAC/Unique ID to what you want it to be - and all sensors get same name.
At least I think that it would work.
And you can select location for every device inside HA already, so no need to do that in configuration of HiGorw sensor too.
If you would move sensor or put it wit another plant, you just rename inside HA, and no need to flash device once again.

**Comment by pesor** [comment]
Version 1.7 is released, and the sleep05 is corrected.
