### ISSUE TITLE
Workaround for BME280 library in context of BT1750

### ISSUE THREAD

**Issue by pzystorm** [pesor/LilyGO-TTGO-HiGrow#3]
Hi,
I dont know if its helpful, but there is a workaround if you **dont** want to include the Adafruit_BME280.h and if you are getting all these weird errors like
ERROR: too long for transmit buffer
ERROR: received NACK on transmit of address
ERROR: received NACK on transmit of data
from the BT1750 code.

Just use this snippet:

```
#define I2C_SDA      25
#define I2C_SCL      26
void setup()
{
    esp_bt_controller_disable();
    Serial.begin(115200);

    //! Sensor power control pin , use deteced must set high
    pinMode(POWER_CTRL, OUTPUT);
    digitalWrite(POWER_CTRL, 1);

    dht12.begin();

    Wire.begin(-1, -1);
    Wire.beginTransmission((uint8_t)0x77);
    Wire.endTransmission();
    Wire.requestFrom((uint8_t)0x77, (byte)1);
    Wire.begin(I2C_SDA, I2C_SCL);

/*
    if (!bmp.begin()) {
        bme_found = false;
    } else {
        bme_found = true;
    }
*/

    if (lightMeter.begin(BH1750::CONTINUOUS_HIGH_RES_MODE)) {
        Serial.println(F("BH1750 Advanced begin"));
    } else {
        Serial.println(F("Error initialising BH1750"));
    }
...
}
```

And then you see "BH1750 Advanced begin" in the console and no error.
If someone can explain that, I am interested in 😃 
I dont know why the ESP32 needs to write and read as a master (to/from some non-extisting adress 0x77, this is the default adress of BME280, but any other adress is working, too), before you can begin the communication with the BT1750.

**Comment by pesor** [comment]
Sorry for late answer, but I have been working on version 3.0.0 for a time now, and just finished it in BETA version.

I tried to implement your code, but got these errors:

[BH1750] ERROR: too long for transmit buffer
Error initialising BH1750
[BH1750] Device is not configured!

So I keep to my solution at the moment.
