### ISSUE TITLE
Battery Voltage inaccurate in lower voltages

### ISSUE THREAD

**Issue by haldi4803** [pesor/LilyGO-TTGO-HiGrow#5]
Hi.

I've done some testing with the Battery Input and powersource and found out that Battery Voltage seems pretty inaccurate in lower voltage regions.

Input Voltage | Read
-- | --
5.0 | 4960
4.9 | 4840
4.8 | 4740
4.7 | 4630
4.6 | 4500
4.5 | 4400
4.4 | 4290
4.3 | 4180
4.2 | 4090
4.1 | 3970
4.0 | 3870
3.9 | 3770
3.8 | 3660
3.7 | 3540
3.6 | 3440
3.5 | 3330
3.4 | 3210
3.3 | 3110
3.2 | 3000
3.1 | 2870
3.0 | 2770
2.9 | 0

Using the correction factor /4095*2*3.3*1100
Using *1180 would be more accurate on Battery operated devices that use 3-3.7V
5V    =  5320mV
3.7V =  3800mV
3V    =  2970mV

**Comment by pesor** [comment]
This looks really good.
At the moment I am upgrading the whole to version 3.0.0, and vill incorporate this in this version.

Version 3.0.0 is a total rewritten solution, where the Home Assistant MQTT Autodiscover is implemented.

I have it running in BETA right now, and it works perfectly, I expect to release version 3.0.0 mid October, and it will be released in a NEW GIthub addres, where this curren address will be available, but there will be a message of discontinution of release 1.x, and a reference to the Github for version 3.0.0.

With Autodiscovery, the tideous work in the configuration.yaml file, will be history, and everything can be handled by the Lovelace frontend.

**Comment by haldi4803** [comment]
Oh, one thing.
When using ESPEasy and deepsleep as soon as the device wakes up the sensores draw quite a bit of power and the voltage drops by roughly 180mV.
So instantly after deep sleep and while reading sensors the voltage MIGHT be off by 180mV.
Haven't tried your code in this environment.

**Comment by pesor** [comment]
I checked and implemented the vref = 1180, and it looks like the voltage looks more correct.

It is implemented in version 3.0.0, which is still in BETA, but will be released soon
