### ISSUE TITLE
Does the unt work with a battery attached ?

### ISSUE THREAD

**Issue by kwiatks** [pesor/LilyGO-TTGO-HiGrow#6]
Hi - not really an issue but a question - does the unit work with a battery ? I have version 1.1 and a  1000 mAH 3.7v battery and it does not power up when I use this battery.  Any help appreciated

**Comment by pesor** [comment]
The TTGO-T-HIGrow module works perfectly on battery. I have currently 10 modules on battery.

Depending on battery quality and components variances mine runs on battery 800mA, from 20 to 40 days.

When you attatch the battery, and an USB cable the red light on the module should Illuminate bright red, and when battery is fully charged the red LED dimms.

You can see the voltage in the MQTT message, and when charging, it should be around +- 4,98 Volt.


Sendt fra min iPhone

Den 12. dec. 2020 kl. 07.00 skrev kwiatks <notifications@github.com>:

﻿

Hi - not really an issue but a question - does the unit work with a battery ? I have version 1.1 and a 1000 mAH 3.7v battery and it does not power up when I use this battery. Any help appreciated
